//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.07.21 at 07:50:33 PM UTC
//


package com.example.soapservice.coarri;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.example.soapservice.coarri package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.soapservice.coarri
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link COARRIINRequest }
     *
     */
    public COARRIINRequest createCOARRIINRequest() {
        return new COARRIINRequest();
    }

    /**
     * Create an instance of {@link COARRIOUTRequest }
     *
     */
    public COARRIOUTRequest createCOARRIOUTRequest() {
        return new COARRIOUTRequest();
    }

    /**
     * Create an instance of {@link COARRIINRequest.VVInfo }
     *
     */
    public COARRIINRequest.VVInfo createCOARRIINRequestVVInfo() {
        return new COARRIINRequest.VVInfo();
    }

    /**
     * Create an instance of {@link COARRIOUTRequest.VVInfo }
     *
     */
    public COARRIOUTRequest.VVInfo createCOARRIOUTRequestVVInfo() {
        return new COARRIOUTRequest.VVInfo();
    }

    /**
     * Create an instance of {@link COARRIResponse }
     *
     */
    public COARRIResponse createCOARRIResponse() {
        return new COARRIResponse();
    }

}
