//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.07.21 at 07:50:33 PM UTC
//


package com.example.soapservice.vvnotice;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.example.soapservice.vvnotice package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.soapservice.vvnotice
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VVNOTICERequest }
     *
     */
    public VVNOTICERequest createVVNOTICERequest() {
        return new VVNOTICERequest();
    }

    /**
     * Create an instance of {@link VVNOTICERequest.Operations }
     *
     */
    public VVNOTICERequest.Operations createVVNOTICERequestOperations() {
        return new VVNOTICERequest.Operations();
    }

    /**
     * Create an instance of {@link VVNOTICERequest.VVInfo }
     *
     */
    public VVNOTICERequest.VVInfo createVVNOTICERequestVVInfo() {
        return new VVNOTICERequest.VVInfo();
    }

    /**
     * Create an instance of {@link VVNOTICEResponse }
     *
     */
    public VVNOTICEResponse createVVNOTICEResponse() {
        return new VVNOTICEResponse();
    }

    /**
     * Create an instance of {@link VVNOTICERequest.Operations.Operation }
     *
     */
    public VVNOTICERequest.Operations.Operation createVVNOTICERequestOperationsOperation() {
        return new VVNOTICERequest.Operations.Operation();
    }

}
