//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.07.21 at 07:50:33 PM UTC
//


package com.example.soapservice.expbol;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.example.soapservice.expbol package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.soapservice.expbol
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EXPBOLRequest }
     *
     */
    public EXPBOLRequest createEXPBOLRequest() {
        return new EXPBOLRequest();
    }

    /**
     * Create an instance of {@link EXPBOLRequest.BOLInfo }
     *
     */
    public EXPBOLRequest.BOLInfo createEXPBOLRequestBOLInfo() {
        return new EXPBOLRequest.BOLInfo();
    }

    /**
     * Create an instance of {@link EXPBOLResponse }
     *
     */
    public EXPBOLResponse createEXPBOLResponse() {
        return new EXPBOLResponse();
    }

}
