//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.07.21 at 07:22:32 PM UTC
//


package com.example.soapservice;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CargoType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CargoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CargoType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PackagingType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="GrossWeight" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NHM" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="DangerousCargo" type="{http://www.example.com/soapservice}DangerousCargoType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CargoType", propOrder = {
    "cargoType",
    "packagingType",
    "quantity",
    "grossWeight",
    "description",
    "nhm",
    "dangerousCargo"
})
public class CargoType {

    @XmlElement(name = "CargoType")
    protected String cargoType;
    @XmlElement(name = "PackagingType", required = true)
    protected String packagingType;
    @XmlElement(name = "Quantity", required = true)
    protected BigInteger quantity;
    @XmlElement(name = "GrossWeight")
    protected float grossWeight;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "NHM", required = true)
    protected String nhm;
    @XmlElement(name = "DangerousCargo")
    protected DangerousCargoType dangerousCargo;

    /**
     * Gets the value of the cargoType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCargoType() {
        return cargoType;
    }

    /**
     * Sets the value of the cargoType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCargoType(String value) {
        this.cargoType = value;
    }

    /**
     * Gets the value of the packagingType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPackagingType() {
        return packagingType;
    }

    /**
     * Sets the value of the packagingType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPackagingType(String value) {
        this.packagingType = value;
    }

    /**
     * Gets the value of the quantity property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setQuantity(BigInteger value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the grossWeight property.
     *
     */
    public float getGrossWeight() {
        return grossWeight;
    }

    /**
     * Sets the value of the grossWeight property.
     *
     */
    public void setGrossWeight(float value) {
        this.grossWeight = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the nhm property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNHM() {
        return nhm;
    }

    /**
     * Sets the value of the nhm property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNHM(String value) {
        this.nhm = value;
    }

    /**
     * Gets the value of the dangerousCargo property.
     *
     * @return
     *     possible object is
     *     {@link DangerousCargoType }
     *
     */
    public DangerousCargoType getDangerousCargo() {
        return dangerousCargo;
    }

    /**
     * Sets the value of the dangerousCargo property.
     *
     * @param value
     *     allowed object is
     *     {@link DangerousCargoType }
     *
     */
    public void setDangerousCargo(DangerousCargoType value) {
        this.dangerousCargo = value;
    }

}
