//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.07.31 at 11:35:57 AM UTC
//


package com.example.soapservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Header" type="{http://www.example.com/soapservice}HeaderType"/&gt;
 *         &lt;element name="VV_info"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Direction" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="VesselName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="VoyageNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="callsign" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="ship_line" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CNT" type="{http://www.example.com/soapservice}CNTType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "vvInfo",
    "cnt"
})
@XmlRootElement(name = "COARRI_IN_Request")
public class COARRIINRequest {

    @XmlElement(name = "Header", required = true)
    protected HeaderType header;
    @XmlElement(name = "VV_info", required = true)
    protected COARRIINRequest.VVInfo vvInfo;
    @XmlElement(name = "CNT", required = true)
    protected CNTType cnt;

    /**
     * Gets the value of the header property.
     *
     * @return
     *     possible object is
     *     {@link HeaderType }
     *
     */
    public HeaderType getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     *
     * @param value
     *     allowed object is
     *     {@link HeaderType }
     *
     */
    public void setHeader(HeaderType value) {
        this.header = value;
    }

    /**
     * Gets the value of the vvInfo property.
     *
     * @return
     *     possible object is
     *     {@link COARRIINRequest.VVInfo }
     *
     */
    public COARRIINRequest.VVInfo getVVInfo() {
        return vvInfo;
    }

    /**
     * Sets the value of the vvInfo property.
     *
     * @param value
     *     allowed object is
     *     {@link COARRIINRequest.VVInfo }
     *
     */
    public void setVVInfo(COARRIINRequest.VVInfo value) {
        this.vvInfo = value;
    }

    /**
     * Gets the value of the cnt property.
     *
     * @return
     *     possible object is
     *     {@link CNTType }
     *
     */
    public CNTType getCNT() {
        return cnt;
    }

    /**
     * Sets the value of the cnt property.
     *
     * @param value
     *     allowed object is
     *     {@link CNTType }
     *
     */
    public void setCNT(CNTType value) {
        this.cnt = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Direction" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="VesselName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="VoyageNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="callsign" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="ship_line" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "direction",
        "vesselName",
        "voyageNumber",
        "callsign",
        "shipLine"
    })
    public static class VVInfo {

        @XmlElement(name = "Direction", required = true)
        protected String direction;
        @XmlElement(name = "VesselName", required = true)
        protected String vesselName;
        @XmlElement(name = "VoyageNumber", required = true)
        protected String voyageNumber;
        @XmlElement(required = true)
        protected String callsign;
        @XmlElement(name = "ship_line", required = true)
        protected String shipLine;

        /**
         * Gets the value of the direction property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getDirection() {
            return direction;
        }

        /**
         * Sets the value of the direction property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setDirection(String value) {
            this.direction = value;
        }

        /**
         * Gets the value of the vesselName property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getVesselName() {
            return vesselName;
        }

        /**
         * Sets the value of the vesselName property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setVesselName(String value) {
            this.vesselName = value;
        }

        /**
         * Gets the value of the voyageNumber property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getVoyageNumber() {
            return voyageNumber;
        }

        /**
         * Sets the value of the voyageNumber property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setVoyageNumber(String value) {
            this.voyageNumber = value;
        }

        /**
         * Gets the value of the callsign property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getCallsign() {
            return callsign;
        }

        /**
         * Sets the value of the callsign property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setCallsign(String value) {
            this.callsign = value;
        }

        /**
         * Gets the value of the shipLine property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getShipLine() {
            return shipLine;
        }

        /**
         * Sets the value of the shipLine property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setShipLine(String value) {
            this.shipLine = value;
        }

    }

}
