//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.08.01 at 03:33:59 AM UTC
//


package com.example.soapservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Header" type="{http://www.example.com/soapservice}HeaderType"/&gt;
 *         &lt;element name="Transport_info"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Direction" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="TransportKind" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="DocNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="TransportNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CNT" type="{http://www.example.com/soapservice}CNTType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "transportInfo",
    "cnt"
})
@XmlRootElement(name = "CODECO_OUT_Request")
public class CODECOOUTRequest {

    @XmlElement(name = "Header", required = true)
    protected HeaderType header;
    @XmlElement(name = "Transport_info", required = true)
    protected CODECOOUTRequest.TransportInfo transportInfo;
    @XmlElement(name = "CNT", required = true)
    protected CNTType cnt;

    /**
     * Gets the value of the header property.
     *
     * @return
     *     possible object is
     *     {@link HeaderType }
     *
     */
    public HeaderType getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     *
     * @param value
     *     allowed object is
     *     {@link HeaderType }
     *
     */
    public void setHeader(HeaderType value) {
        this.header = value;
    }

    /**
     * Gets the value of the transportInfo property.
     *
     * @return
     *     possible object is
     *     {@link CODECOOUTRequest.TransportInfo }
     *
     */
    public CODECOOUTRequest.TransportInfo getTransportInfo() {
        return transportInfo;
    }

    /**
     * Sets the value of the transportInfo property.
     *
     * @param value
     *     allowed object is
     *     {@link CODECOOUTRequest.TransportInfo }
     *
     */
    public void setTransportInfo(CODECOOUTRequest.TransportInfo value) {
        this.transportInfo = value;
    }

    /**
     * Gets the value of the cnt property.
     *
     * @return
     *     possible object is
     *     {@link CNTType }
     *
     */
    public CNTType getCNT() {
        return cnt;
    }

    /**
     * Sets the value of the cnt property.
     *
     * @param value
     *     allowed object is
     *     {@link CNTType }
     *
     */
    public void setCNT(CNTType value) {
        this.cnt = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Direction" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="TransportKind" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="DocNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="TransportNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "direction",
        "transportKind",
        "docNumber",
        "transportNumber"
    })
    public static class TransportInfo {

        @XmlElement(name = "Direction", required = true)
        protected String direction;
        @XmlElement(name = "TransportKind", required = true)
        protected String transportKind;
        @XmlElement(name = "DocNumber", required = true)
        protected String docNumber;
        @XmlElement(name = "TransportNumber", required = true)
        protected String transportNumber;

        /**
         * Gets the value of the direction property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getDirection() {
            return direction;
        }

        /**
         * Sets the value of the direction property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setDirection(String value) {
            this.direction = value;
        }

        /**
         * Gets the value of the transportKind property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getTransportKind() {
            return transportKind;
        }

        /**
         * Sets the value of the transportKind property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setTransportKind(String value) {
            this.transportKind = value;
        }

        /**
         * Gets the value of the docNumber property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getDocNumber() {
            return docNumber;
        }

        /**
         * Sets the value of the docNumber property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setDocNumber(String value) {
            this.docNumber = value;
        }

        /**
         * Gets the value of the transportNumber property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getTransportNumber() {
            return transportNumber;
        }

        /**
         * Sets the value of the transportNumber property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setTransportNumber(String value) {
            this.transportNumber = value;
        }

    }

}
