//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.07.21 at 08:06:50 PM UTC
//


package com.example.soapservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContainerType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ContainerType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ContainerNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Cont_syncid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="TareWeight" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *         &lt;element name="NetWeight" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *         &lt;element name="GrossWeight" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *         &lt;element name="BruttoWeight" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *         &lt;element name="Iso" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Empty" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="OperationDateTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LoadPort" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DischPort" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LoadRollback" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="Cargos" type="{http://www.example.com/soapservice}CargosType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContainerType", propOrder = {
    "containerNumber",
    "contSyncid",
    "tareWeight",
    "netWeight",
    "grossWeight",
    "bruttoWeight",
    "iso",
    "empty",
    "operationDateTime",
    "loadPort",
    "dischPort",
    "loadRollback",
    "cargos"
})
public class ContainerType {

    @XmlElement(name = "ContainerNumber", required = true)
    protected String containerNumber;
    @XmlElement(name = "Cont_syncid", required = true)
    protected String contSyncid;
    @XmlElement(name = "TareWeight")
    protected Float tareWeight;
    @XmlElement(name = "NetWeight")
    protected Float netWeight;
    @XmlElement(name = "GrossWeight")
    protected Float grossWeight;
    @XmlElement(name = "BruttoWeight")
    protected Float bruttoWeight;
    @XmlElement(name = "Iso")
    protected String iso;
    @XmlElement(name = "Empty")
    protected Boolean empty;
    @XmlElement(name = "OperationDateTime")
    protected String operationDateTime;
    @XmlElement(name = "LoadPort")
    protected String loadPort;
    @XmlElement(name = "DischPort")
    protected String dischPort;
    @XmlElement(name = "LoadRollback")
    protected Boolean loadRollback;
    @XmlElement(name = "Cargos")
    protected CargosType cargos;

    /**
     * Gets the value of the containerNumber property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getContainerNumber() {
        return containerNumber;
    }

    /**
     * Sets the value of the containerNumber property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setContainerNumber(String value) {
        this.containerNumber = value;
    }

    /**
     * Gets the value of the contSyncid property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getContSyncid() {
        return contSyncid;
    }

    /**
     * Sets the value of the contSyncid property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setContSyncid(String value) {
        this.contSyncid = value;
    }

    /**
     * Gets the value of the tareWeight property.
     *
     * @return
     *     possible object is
     *     {@link Float }
     *
     */
    public Float getTareWeight() {
        return tareWeight;
    }

    /**
     * Sets the value of the tareWeight property.
     *
     * @param value
     *     allowed object is
     *     {@link Float }
     *
     */
    public void setTareWeight(Float value) {
        this.tareWeight = value;
    }

    /**
     * Gets the value of the netWeight property.
     *
     * @return
     *     possible object is
     *     {@link Float }
     *
     */
    public Float getNetWeight() {
        return netWeight;
    }

    /**
     * Sets the value of the netWeight property.
     *
     * @param value
     *     allowed object is
     *     {@link Float }
     *
     */
    public void setNetWeight(Float value) {
        this.netWeight = value;
    }

    /**
     * Gets the value of the grossWeight property.
     *
     * @return
     *     possible object is
     *     {@link Float }
     *
     */
    public Float getGrossWeight() {
        return grossWeight;
    }

    /**
     * Sets the value of the grossWeight property.
     *
     * @param value
     *     allowed object is
     *     {@link Float }
     *
     */
    public void setGrossWeight(Float value) {
        this.grossWeight = value;
    }

    /**
     * Gets the value of the bruttoWeight property.
     *
     * @return
     *     possible object is
     *     {@link Float }
     *
     */
    public Float getBruttoWeight() {
        return bruttoWeight;
    }

    /**
     * Sets the value of the bruttoWeight property.
     *
     * @param value
     *     allowed object is
     *     {@link Float }
     *
     */
    public void setBruttoWeight(Float value) {
        this.bruttoWeight = value;
    }

    /**
     * Gets the value of the iso property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIso() {
        return iso;
    }

    /**
     * Sets the value of the iso property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIso(String value) {
        this.iso = value;
    }

    /**
     * Gets the value of the empty property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isEmpty() {
        return empty;
    }

    /**
     * Sets the value of the empty property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setEmpty(Boolean value) {
        this.empty = value;
    }

    /**
     * Gets the value of the operationDateTime property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOperationDateTime() {
        return operationDateTime;
    }

    /**
     * Sets the value of the operationDateTime property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOperationDateTime(String value) {
        this.operationDateTime = value;
    }

    /**
     * Gets the value of the loadPort property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLoadPort() {
        return loadPort;
    }

    /**
     * Sets the value of the loadPort property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLoadPort(String value) {
        this.loadPort = value;
    }

    /**
     * Gets the value of the dischPort property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDischPort() {
        return dischPort;
    }

    /**
     * Sets the value of the dischPort property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDischPort(String value) {
        this.dischPort = value;
    }

    /**
     * Gets the value of the loadRollback property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isLoadRollback() {
        return loadRollback;
    }

    /**
     * Sets the value of the loadRollback property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setLoadRollback(Boolean value) {
        this.loadRollback = value;
    }

    /**
     * Gets the value of the cargos property.
     *
     * @return
     *     possible object is
     *     {@link CargosType }
     *
     */
    public CargosType getCargos() {
        return cargos;
    }

    /**
     * Sets the value of the cargos property.
     *
     * @param value
     *     allowed object is
     *     {@link CargosType }
     *
     */
    public void setCargos(CargosType value) {
        this.cargos = value;
    }

}
