//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.07.21 at 07:22:32 PM UTC
//


package com.example.soapservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DangerousCargoType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DangerousCargoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ProperShippingName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ImdgClass" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DangerousCargoType", propOrder = {
    "properShippingName",
    "imdgClass"
})
public class DangerousCargoType {

    @XmlElement(name = "ProperShippingName")
    protected String properShippingName;
    @XmlElement(name = "ImdgClass")
    protected String imdgClass;

    /**
     * Gets the value of the properShippingName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getProperShippingName() {
        return properShippingName;
    }

    /**
     * Sets the value of the properShippingName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setProperShippingName(String value) {
        this.properShippingName = value;
    }

    /**
     * Gets the value of the imdgClass property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getImdgClass() {
        return imdgClass;
    }

    /**
     * Sets the value of the imdgClass property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setImdgClass(String value) {
        this.imdgClass = value;
    }

}
