//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.07.31 at 06:11:07 PM UTC
//


package com.example.soapservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Header" type="{http://www.example.com/soapservice}HeaderType"/&gt;
 *         &lt;element name="BOL_info"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="VesselName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="VoyageNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="bolNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="bolDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="agent" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="LoadPort" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="DischPort" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="SenderCargo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="ReceiverCargo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="marksandNumbers" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="FreightAndCharges" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CNT" type="{http://www.example.com/soapservice}CNTType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "bolInfo",
    "cnt"
})
@XmlRootElement(name = "EXP_BOL_Request")
public class EXPBOLRequest {

    @XmlElement(name = "Header", required = true)
    protected HeaderType header;
    @XmlElement(name = "BOL_info", required = true)
    protected EXPBOLRequest.BOLInfo bolInfo;
    @XmlElement(name = "CNT", required = true)
    protected CNTType cnt;

    /**
     * Gets the value of the header property.
     *
     * @return
     *     possible object is
     *     {@link HeaderType }
     *
     */
    public HeaderType getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     *
     * @param value
     *     allowed object is
     *     {@link HeaderType }
     *
     */
    public void setHeader(HeaderType value) {
        this.header = value;
    }

    /**
     * Gets the value of the bolInfo property.
     *
     * @return
     *     possible object is
     *     {@link EXPBOLRequest.BOLInfo }
     *
     */
    public EXPBOLRequest.BOLInfo getBOLInfo() {
        return bolInfo;
    }

    /**
     * Sets the value of the bolInfo property.
     *
     * @param value
     *     allowed object is
     *     {@link EXPBOLRequest.BOLInfo }
     *
     */
    public void setBOLInfo(EXPBOLRequest.BOLInfo value) {
        this.bolInfo = value;
    }

    /**
     * Gets the value of the cnt property.
     *
     * @return
     *     possible object is
     *     {@link CNTType }
     *
     */
    public CNTType getCNT() {
        return cnt;
    }

    /**
     * Sets the value of the cnt property.
     *
     * @param value
     *     allowed object is
     *     {@link CNTType }
     *
     */
    public void setCNT(CNTType value) {
        this.cnt = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="VesselName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="VoyageNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="bolNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="bolDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="agent" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="LoadPort" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="DischPort" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="SenderCargo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="ReceiverCargo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="marksandNumbers" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="FreightAndCharges" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vesselName",
        "voyageNumber",
        "bolNumber",
        "bolDate",
        "agent",
        "loadPort",
        "dischPort",
        "senderCargo",
        "receiverCargo",
        "marksandNumbers",
        "freightAndCharges"
    })
    public static class BOLInfo {

        @XmlElement(name = "VesselName", required = true)
        protected String vesselName;
        @XmlElement(name = "VoyageNumber", required = true)
        protected String voyageNumber;
        @XmlElement(required = true)
        protected String bolNumber;
        @XmlElement(required = true)
        protected String bolDate;
        @XmlElement(required = true)
        protected String agent;
        @XmlElement(name = "LoadPort", required = true)
        protected String loadPort;
        @XmlElement(name = "DischPort", required = true)
        protected String dischPort;
        @XmlElement(name = "SenderCargo", required = true)
        protected String senderCargo;
        @XmlElement(name = "ReceiverCargo", required = true)
        protected String receiverCargo;
        @XmlElement(required = true)
        protected String marksandNumbers;
        @XmlElement(name = "FreightAndCharges", required = true)
        protected String freightAndCharges;

        /**
         * Gets the value of the vesselName property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getVesselName() {
            return vesselName;
        }

        /**
         * Sets the value of the vesselName property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setVesselName(String value) {
            this.vesselName = value;
        }

        /**
         * Gets the value of the voyageNumber property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getVoyageNumber() {
            return voyageNumber;
        }

        /**
         * Sets the value of the voyageNumber property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setVoyageNumber(String value) {
            this.voyageNumber = value;
        }

        /**
         * Gets the value of the bolNumber property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getBolNumber() {
            return bolNumber;
        }

        /**
         * Sets the value of the bolNumber property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setBolNumber(String value) {
            this.bolNumber = value;
        }

        /**
         * Gets the value of the bolDate property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getBolDate() {
            return bolDate;
        }

        /**
         * Sets the value of the bolDate property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setBolDate(String value) {
            this.bolDate = value;
        }

        /**
         * Gets the value of the agent property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getAgent() {
            return agent;
        }

        /**
         * Sets the value of the agent property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setAgent(String value) {
            this.agent = value;
        }

        /**
         * Gets the value of the loadPort property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getLoadPort() {
            return loadPort;
        }

        /**
         * Sets the value of the loadPort property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setLoadPort(String value) {
            this.loadPort = value;
        }

        /**
         * Gets the value of the dischPort property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getDischPort() {
            return dischPort;
        }

        /**
         * Sets the value of the dischPort property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setDischPort(String value) {
            this.dischPort = value;
        }

        /**
         * Gets the value of the senderCargo property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getSenderCargo() {
            return senderCargo;
        }

        /**
         * Sets the value of the senderCargo property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setSenderCargo(String value) {
            this.senderCargo = value;
        }

        /**
         * Gets the value of the receiverCargo property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getReceiverCargo() {
            return receiverCargo;
        }

        /**
         * Sets the value of the receiverCargo property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setReceiverCargo(String value) {
            this.receiverCargo = value;
        }

        /**
         * Gets the value of the marksandNumbers property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getMarksandNumbers() {
            return marksandNumbers;
        }

        /**
         * Sets the value of the marksandNumbers property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setMarksandNumbers(String value) {
            this.marksandNumbers = value;
        }

        /**
         * Gets the value of the freightAndCharges property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getFreightAndCharges() {
            return freightAndCharges;
        }

        /**
         * Sets the value of the freightAndCharges property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setFreightAndCharges(String value) {
            this.freightAndCharges = value;
        }

    }

}
