//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.07.21 at 07:22:32 PM UTC
//


package com.example.soapservice;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for INVType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="INVType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="WagonNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="InvoiceNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="WagonType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="PreviousStationCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="SenderCargo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ReceiverCargo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Etd" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="Forwarder" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Forwarder_bin" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="SendingCountry" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RecipientCountry" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CNT" type="{http://www.example.com/soapservice}CNTType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "INVType", propOrder = {
    "wagonNumber",
    "invoiceNumber",
    "wagonType",
    "previousStationCode",
    "senderCargo",
    "receiverCargo",
    "etd",
    "forwarder",
    "forwarderBin",
    "sendingCountry",
    "recipientCountry",
    "cnt"
})
public class INVType {

    @XmlElement(name = "WagonNumber", required = true)
    protected String wagonNumber;
    @XmlElement(name = "InvoiceNumber", required = true)
    protected String invoiceNumber;
    @XmlElement(name = "WagonType", required = true)
    protected String wagonType;
    @XmlElement(name = "PreviousStationCode", required = true)
    protected String previousStationCode;
    @XmlElement(name = "SenderCargo", required = true)
    protected String senderCargo;
    @XmlElement(name = "ReceiverCargo", required = true)
    protected String receiverCargo;
    @XmlElement(name = "Etd", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar etd;
    @XmlElement(name = "Forwarder")
    protected String forwarder;
    @XmlElement(name = "Forwarder_bin", required = true)
    protected String forwarderBin;
    @XmlElement(name = "SendingCountry")
    protected String sendingCountry;
    @XmlElement(name = "RecipientCountry")
    protected String recipientCountry;
    @XmlElement(name = "CNT", required = true)
    protected CNTType cnt;

    /**
     * Gets the value of the wagonNumber property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getWagonNumber() {
        return wagonNumber;
    }

    /**
     * Sets the value of the wagonNumber property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setWagonNumber(String value) {
        this.wagonNumber = value;
    }

    /**
     * Gets the value of the invoiceNumber property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getInvoiceNumber() {
        return invoiceNumber;
    }

    /**
     * Sets the value of the invoiceNumber property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setInvoiceNumber(String value) {
        this.invoiceNumber = value;
    }

    /**
     * Gets the value of the wagonType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getWagonType() {
        return wagonType;
    }

    /**
     * Sets the value of the wagonType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setWagonType(String value) {
        this.wagonType = value;
    }

    /**
     * Gets the value of the previousStationCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPreviousStationCode() {
        return previousStationCode;
    }

    /**
     * Sets the value of the previousStationCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPreviousStationCode(String value) {
        this.previousStationCode = value;
    }

    /**
     * Gets the value of the senderCargo property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSenderCargo() {
        return senderCargo;
    }

    /**
     * Sets the value of the senderCargo property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSenderCargo(String value) {
        this.senderCargo = value;
    }

    /**
     * Gets the value of the receiverCargo property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getReceiverCargo() {
        return receiverCargo;
    }

    /**
     * Sets the value of the receiverCargo property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setReceiverCargo(String value) {
        this.receiverCargo = value;
    }

    /**
     * Gets the value of the etd property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getEtd() {
        return etd;
    }

    /**
     * Sets the value of the etd property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setEtd(XMLGregorianCalendar value) {
        this.etd = value;
    }

    /**
     * Gets the value of the forwarder property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getForwarder() {
        return forwarder;
    }

    /**
     * Sets the value of the forwarder property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setForwarder(String value) {
        this.forwarder = value;
    }

    /**
     * Gets the value of the forwarderBin property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getForwarderBin() {
        return forwarderBin;
    }

    /**
     * Sets the value of the forwarderBin property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setForwarderBin(String value) {
        this.forwarderBin = value;
    }

    /**
     * Gets the value of the sendingCountry property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSendingCountry() {
        return sendingCountry;
    }

    /**
     * Sets the value of the sendingCountry property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSendingCountry(String value) {
        this.sendingCountry = value;
    }

    /**
     * Gets the value of the recipientCountry property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRecipientCountry() {
        return recipientCountry;
    }

    /**
     * Sets the value of the recipientCountry property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRecipientCountry(String value) {
        this.recipientCountry = value;
    }

    /**
     * Gets the value of the cnt property.
     *
     * @return
     *     possible object is
     *     {@link CNTType }
     *
     */
    public CNTType getCNT() {
        return cnt;
    }

    /**
     * Sets the value of the cnt property.
     *
     * @param value
     *     allowed object is
     *     {@link CNTType }
     *
     */
    public void setCNT(CNTType value) {
        this.cnt = value;
    }

}
