//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.07.21 at 07:22:32 PM UTC
//


package com.example.soapservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MessageType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="MessageType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Header" type="{http://www.example.com/soapservice}HeaderType"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="Payload" type="{http://www.example.com/soapservice}PayloadType"/&gt;
 *           &lt;element name="CODECO" type="{http://www.example.com/soapservice}CODECOType"/&gt;
 *           &lt;element name="COARRI" type="{http://www.example.com/soapservice}COARRIType"/&gt;
 *           &lt;element name="VV_NOTICE" type="{http://www.example.com/soapservice}VV_NOTICEType"/&gt;
 *           &lt;element name="EXP_BOL" type="{http://www.example.com/soapservice}EXP_BOLType"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MessageType", propOrder = {
    "header",
    "payload",
    "codeco",
    "coarri",
    "vvnotice",
    "expbol"
})
public class MessageType {

    @XmlElement(name = "Header", required = true)
    protected HeaderType header;
    @XmlElement(name = "Payload")
    protected PayloadType payload;
    @XmlElement(name = "CODECO")
    protected CODECOType codeco;
    @XmlElement(name = "COARRI")
    protected COARRIType coarri;
    @XmlElement(name = "VV_NOTICE")
    protected VVNOTICEType vvnotice;
    @XmlElement(name = "EXP_BOL")
    protected EXPBOLType expbol;

    /**
     * Gets the value of the header property.
     *
     * @return
     *     possible object is
     *     {@link HeaderType }
     *
     */
    public HeaderType getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     *
     * @param value
     *     allowed object is
     *     {@link HeaderType }
     *
     */
    public void setHeader(HeaderType value) {
        this.header = value;
    }

    /**
     * Gets the value of the payload property.
     *
     * @return
     *     possible object is
     *     {@link PayloadType }
     *
     */
    public PayloadType getPayload() {
        return payload;
    }

    /**
     * Sets the value of the payload property.
     *
     * @param value
     *     allowed object is
     *     {@link PayloadType }
     *
     */
    public void setPayload(PayloadType value) {
        this.payload = value;
    }

    /**
     * Gets the value of the codeco property.
     *
     * @return
     *     possible object is
     *     {@link CODECOType }
     *
     */
    public CODECOType getCODECO() {
        return codeco;
    }

    /**
     * Sets the value of the codeco property.
     *
     * @param value
     *     allowed object is
     *     {@link CODECOType }
     *
     */
    public void setCODECO(CODECOType value) {
        this.codeco = value;
    }

    /**
     * Gets the value of the coarri property.
     *
     * @return
     *     possible object is
     *     {@link COARRIType }
     *
     */
    public COARRIType getCOARRI() {
        return coarri;
    }

    /**
     * Sets the value of the coarri property.
     *
     * @param value
     *     allowed object is
     *     {@link COARRIType }
     *
     */
    public void setCOARRI(COARRIType value) {
        this.coarri = value;
    }

    /**
     * Gets the value of the vvnotice property.
     *
     * @return
     *     possible object is
     *     {@link VVNOTICEType }
     *
     */
    public VVNOTICEType getVVNOTICE() {
        return vvnotice;
    }

    /**
     * Sets the value of the vvnotice property.
     *
     * @param value
     *     allowed object is
     *     {@link VVNOTICEType }
     *
     */
    public void setVVNOTICE(VVNOTICEType value) {
        this.vvnotice = value;
    }

    /**
     * Gets the value of the expbol property.
     *
     * @return
     *     possible object is
     *     {@link EXPBOLType }
     *
     */
    public EXPBOLType getEXPBOL() {
        return expbol;
    }

    /**
     * Sets the value of the expbol property.
     *
     * @param value
     *     allowed object is
     *     {@link EXPBOLType }
     *
     */
    public void setEXPBOL(EXPBOLType value) {
        this.expbol = value;
    }

}
