//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.07.21 at 07:22:32 PM UTC
//


package com.example.soapservice;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.example.soapservice package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.soapservice
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Data }
     *
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link MessageType }
     *
     */
    public MessageType createMessageType() {
        return new MessageType();
    }

    /**
     * Create an instance of {@link GetResponse }
     *
     */
    public GetResponse createGetResponse() {
        return new GetResponse();
    }

    /**
     * Create an instance of {@link ResponseDataType }
     *
     */
    public ResponseDataType createResponseDataType() {
        return new ResponseDataType();
    }

    /**
     * Create an instance of {@link HeaderType }
     *
     */
    public HeaderType createHeaderType() {
        return new HeaderType();
    }

    /**
     * Create an instance of {@link PayloadType }
     *
     */
    public PayloadType createPayloadType() {
        return new PayloadType();
    }

    /**
     * Create an instance of {@link INVType }
     *
     */
    public INVType createINVType() {
        return new INVType();
    }

    /**
     * Create an instance of {@link CNTType }
     *
     */
    public CNTType createCNTType() {
        return new CNTType();
    }

    /**
     * Create an instance of {@link ContainersType }
     *
     */
    public ContainersType createContainersType() {
        return new ContainersType();
    }

    /**
     * Create an instance of {@link ContainerType }
     *
     */
    public ContainerType createContainerType() {
        return new ContainerType();
    }

    /**
     * Create an instance of {@link TemperatureType }
     *
     */
    public TemperatureType createTemperatureType() {
        return new TemperatureType();
    }

    /**
     * Create an instance of {@link SealsType }
     *
     */
    public SealsType createSealsType() {
        return new SealsType();
    }

    /**
     * Create an instance of {@link SealType }
     *
     */
    public SealType createSealType() {
        return new SealType();
    }

    /**
     * Create an instance of {@link CargosType }
     *
     */
    public CargosType createCargosType() {
        return new CargosType();
    }

    /**
     * Create an instance of {@link CargoType }
     *
     */
    public CargoType createCargoType() {
        return new CargoType();
    }

    /**
     * Create an instance of {@link DangerousCargoType }
     *
     */
    public DangerousCargoType createDangerousCargoType() {
        return new DangerousCargoType();
    }

    /**
     * Create an instance of {@link CODECOType }
     *
     */
    public CODECOType createCODECOType() {
        return new CODECOType();
    }

    /**
     * Create an instance of {@link TransportInfoType }
     *
     */
    public TransportInfoType createTransportInfoType() {
        return new TransportInfoType();
    }

    /**
     * Create an instance of {@link COARRIType }
     *
     */
    public COARRIType createCOARRIType() {
        return new COARRIType();
    }

    /**
     * Create an instance of {@link VVInfoType }
     *
     */
    public VVInfoType createVVInfoType() {
        return new VVInfoType();
    }

    /**
     * Create an instance of {@link VVNOTICEType }
     *
     */
    public VVNOTICEType createVVNOTICEType() {
        return new VVNOTICEType();
    }

    /**
     * Create an instance of {@link OperationsType }
     *
     */
    public OperationsType createOperationsType() {
        return new OperationsType();
    }

    /**
     * Create an instance of {@link OperationType }
     *
     */
    public OperationType createOperationType() {
        return new OperationType();
    }

    /**
     * Create an instance of {@link EXPBOLType }
     *
     */
    public EXPBOLType createEXPBOLType() {
        return new EXPBOLType();
    }

    /**
     * Create an instance of {@link BOLInfoType }
     *
     */
    public BOLInfoType createBOLInfoType() {
        return new BOLInfoType();
    }

    /**
     * Create an instance of {@link ResponseMessage }
     *
     */
    public ResponseMessage createResponseMessage() {
        return new ResponseMessage();
    }

}
