//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.07.31 at 11:35:57 AM UTC
//


package com.example.soapservice;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.example.soapservice package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.soapservice
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CODECOINRequest }
     *
     */
    public CODECOINRequest createCODECOINRequest() {
        return new CODECOINRequest();
    }

    /**
     * Create an instance of {@link CODECOOUTRequest }
     *
     */
    public CODECOOUTRequest createCODECOOUTRequest() {
        return new CODECOOUTRequest();
    }

    /**
     * Create an instance of {@link COARRIINRequest }
     *
     */
    public COARRIINRequest createCOARRIINRequest() {
        return new COARRIINRequest();
    }

    /**
     * Create an instance of {@link COARRIOUTRequest }
     *
     */
    public COARRIOUTRequest createCOARRIOUTRequest() {
        return new COARRIOUTRequest();
    }

    /**
     * Create an instance of {@link VVNOTICERequest }
     *
     */
    public VVNOTICERequest createVVNOTICERequest() {
        return new VVNOTICERequest();
    }

    /**
     * Create an instance of {@link EXPBOLRequest }
     *
     */
    public EXPBOLRequest createEXPBOLRequest() {
        return new EXPBOLRequest();
    }

    /**
     * Create an instance of {@link VVNOTICERequest.Operations }
     *
     */
    public VVNOTICERequest.Operations createVVNOTICERequestOperations() {
        return new VVNOTICERequest.Operations();
    }

    /**
     * Create an instance of {@link HeaderType }
     *
     */
    public HeaderType createHeaderType() {
        return new HeaderType();
    }

    /**
     * Create an instance of {@link CODECOINRequest.TransportInfo }
     *
     */
    public CODECOINRequest.TransportInfo createCODECOINRequestTransportInfo() {
        return new CODECOINRequest.TransportInfo();
    }

    /**
     * Create an instance of {@link CNTType }
     *
     */
    public CNTType createCNTType() {
        return new CNTType();
    }

    /**
     * Create an instance of {@link CODECOOUTRequest.TransportInfo }
     *
     */
    public CODECOOUTRequest.TransportInfo createCODECOOUTRequestTransportInfo() {
        return new CODECOOUTRequest.TransportInfo();
    }

    /**
     * Create an instance of {@link COARRIINRequest.VVInfo }
     *
     */
    public COARRIINRequest.VVInfo createCOARRIINRequestVVInfo() {
        return new COARRIINRequest.VVInfo();
    }

    /**
     * Create an instance of {@link COARRIOUTRequest.VVInfo }
     *
     */
    public COARRIOUTRequest.VVInfo createCOARRIOUTRequestVVInfo() {
        return new COARRIOUTRequest.VVInfo();
    }

    /**
     * Create an instance of {@link VVNOTICERequest.VVInfo }
     *
     */
    public VVNOTICERequest.VVInfo createVVNOTICERequestVVInfo() {
        return new VVNOTICERequest.VVInfo();
    }

    /**
     * Create an instance of {@link EXPBOLRequest.BOLInfo }
     *
     */
    public EXPBOLRequest.BOLInfo createEXPBOLRequestBOLInfo() {
        return new EXPBOLRequest.BOLInfo();
    }

    /**
     * Create an instance of {@link Response }
     *
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link SuccessResponse }
     *
     */
    public SuccessResponse createSuccessResponse() {
        return new SuccessResponse();
    }

    /**
     * Create an instance of {@link ErrorResponse }
     *
     */
    public ErrorResponse createErrorResponse() {
        return new ErrorResponse();
    }

    /**
     * Create an instance of {@link ContainerType }
     *
     */
    public ContainerType createContainerType() {
        return new ContainerType();
    }

    /**
     * Create an instance of {@link CargosType }
     *
     */
    public CargosType createCargosType() {
        return new CargosType();
    }

    /**
     * Create an instance of {@link CargoType }
     *
     */
    public CargoType createCargoType() {
        return new CargoType();
    }

    /**
     * Create an instance of {@link VVNOTICERequest.Operations.Operation }
     *
     */
    public VVNOTICERequest.Operations.Operation createVVNOTICERequestOperationsOperation() {
        return new VVNOTICERequest.Operations.Operation();
    }

}
