//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.07.21 at 07:22:32 PM UTC
//


package com.example.soapservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OperationType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="OperationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OperType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="OperDateTime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OperationType", propOrder = {
    "operType",
    "operDateTime"
})
public class OperationType {

    @XmlElement(name = "OperType", required = true)
    protected String operType;
    @XmlElement(name = "OperDateTime", required = true)
    protected String operDateTime;

    /**
     * Gets the value of the operType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOperType() {
        return operType;
    }

    /**
     * Sets the value of the operType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOperType(String value) {
        this.operType = value;
    }

    /**
     * Gets the value of the operDateTime property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOperDateTime() {
        return operDateTime;
    }

    /**
     * Sets the value of the operDateTime property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOperDateTime(String value) {
        this.operDateTime = value;
    }

}
