//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.07.31 at 06:11:07 PM UTC
//


package com.example.soapservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="Success" type="{http://www.example.com/soapservice}SuccessResponse"/&gt;
 *         &lt;element name="Error" type="{http://www.example.com/soapservice}ErrorResponse"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "success",
    "error"
})
@XmlRootElement(name = "Response")
public class Response {

    @XmlElement(name = "Success")
    protected SuccessResponse success;
    @XmlElement(name = "Error")
    protected ErrorResponse error;

    /**
     * Gets the value of the success property.
     *
     * @return
     *     possible object is
     *     {@link SuccessResponse }
     *
     */
    public SuccessResponse getSuccess() {
        return success;
    }

    /**
     * Sets the value of the success property.
     *
     * @param value
     *     allowed object is
     *     {@link SuccessResponse }
     *
     */
    public void setSuccess(SuccessResponse value) {
        this.success = value;
    }

    /**
     * Gets the value of the error property.
     *
     * @return
     *     possible object is
     *     {@link ErrorResponse }
     *
     */
    public ErrorResponse getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     *
     * @param value
     *     allowed object is
     *     {@link ErrorResponse }
     *
     */
    public void setError(ErrorResponse value) {
        this.error = value;
    }

}
