//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.07.21 at 07:22:32 PM UTC
//


package com.example.soapservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Transport_infoType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Transport_infoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Direction"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="IN"/&gt;
 *               &lt;enumeration value="OUT"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="TransportKind" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="DocNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="TransportNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Transport_infoType", propOrder = {
    "direction",
    "transportKind",
    "docNumber",
    "transportNumber"
})
public class TransportInfoType {

    @XmlElement(name = "Direction", required = true)
    protected String direction;
    @XmlElement(name = "TransportKind", required = true)
    protected String transportKind;
    @XmlElement(name = "DocNumber", required = true)
    protected String docNumber;
    @XmlElement(name = "TransportNumber", required = true)
    protected String transportNumber;

    /**
     * Gets the value of the direction property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDirection(String value) {
        this.direction = value;
    }

    /**
     * Gets the value of the transportKind property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTransportKind() {
        return transportKind;
    }

    /**
     * Sets the value of the transportKind property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTransportKind(String value) {
        this.transportKind = value;
    }

    /**
     * Gets the value of the docNumber property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDocNumber() {
        return docNumber;
    }

    /**
     * Sets the value of the docNumber property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDocNumber(String value) {
        this.docNumber = value;
    }

    /**
     * Gets the value of the transportNumber property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTransportNumber() {
        return transportNumber;
    }

    /**
     * Sets the value of the transportNumber property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTransportNumber(String value) {
        this.transportNumber = value;
    }

}
