//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.07.21 at 07:22:32 PM UTC
//


package com.example.soapservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VV_infoType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="VV_infoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Direction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="VesselName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="VoyageNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="callsign" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ship_line" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="PortCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="VoyageNumberIn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="VoyageNumberOut" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VV_infoType", propOrder = {
    "direction",
    "vesselName",
    "voyageNumber",
    "callsign",
    "shipLine",
    "portCode",
    "voyageNumberIn",
    "voyageNumberOut"
})
public class VVInfoType {

    @XmlElement(name = "Direction")
    protected String direction;
    @XmlElement(name = "VesselName", required = true)
    protected String vesselName;
    @XmlElement(name = "VoyageNumber", required = true)
    protected String voyageNumber;
    @XmlElement(required = true)
    protected String callsign;
    @XmlElement(name = "ship_line", required = true)
    protected String shipLine;
    @XmlElement(name = "PortCode")
    protected String portCode;
    @XmlElement(name = "VoyageNumberIn")
    protected String voyageNumberIn;
    @XmlElement(name = "VoyageNumberOut")
    protected String voyageNumberOut;

    /**
     * Gets the value of the direction property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDirection(String value) {
        this.direction = value;
    }

    /**
     * Gets the value of the vesselName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVesselName() {
        return vesselName;
    }

    /**
     * Sets the value of the vesselName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVesselName(String value) {
        this.vesselName = value;
    }

    /**
     * Gets the value of the voyageNumber property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVoyageNumber() {
        return voyageNumber;
    }

    /**
     * Sets the value of the voyageNumber property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVoyageNumber(String value) {
        this.voyageNumber = value;
    }

    /**
     * Gets the value of the callsign property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCallsign() {
        return callsign;
    }

    /**
     * Sets the value of the callsign property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCallsign(String value) {
        this.callsign = value;
    }

    /**
     * Gets the value of the shipLine property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getShipLine() {
        return shipLine;
    }

    /**
     * Sets the value of the shipLine property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setShipLine(String value) {
        this.shipLine = value;
    }

    /**
     * Gets the value of the portCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPortCode() {
        return portCode;
    }

    /**
     * Sets the value of the portCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPortCode(String value) {
        this.portCode = value;
    }

    /**
     * Gets the value of the voyageNumberIn property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVoyageNumberIn() {
        return voyageNumberIn;
    }

    /**
     * Sets the value of the voyageNumberIn property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVoyageNumberIn(String value) {
        this.voyageNumberIn = value;
    }

    /**
     * Gets the value of the voyageNumberOut property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVoyageNumberOut() {
        return voyageNumberOut;
    }

    /**
     * Sets the value of the voyageNumberOut property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVoyageNumberOut(String value) {
        this.voyageNumberOut = value;
    }

}
