//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.07.31 at 06:11:07 PM UTC
//


package com.example.soapservice;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Header" type="{http://www.example.com/soapservice}HeaderType"/&gt;
 *         &lt;element name="VV_info"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="PortCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="VesselName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="VoyageNumberIn" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="VoyageNumberOut" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="callsign" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="ship_line" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Operations"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Operation" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="OperType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="OperDateTime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CNT" type="{http://www.example.com/soapservice}CNTType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "vvInfo",
    "operations",
    "cnt"
})
@XmlRootElement(name = "VV_NOTICE_Request")
public class VVNOTICERequest {

    @XmlElement(name = "Header", required = true)
    protected HeaderType header;
    @XmlElement(name = "VV_info", required = true)
    protected VVNOTICERequest.VVInfo vvInfo;
    @XmlElement(name = "Operations", required = true)
    protected VVNOTICERequest.Operations operations;
    @XmlElement(name = "CNT", required = true)
    protected CNTType cnt;

    /**
     * Gets the value of the header property.
     *
     * @return
     *     possible object is
     *     {@link HeaderType }
     *
     */
    public HeaderType getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     *
     * @param value
     *     allowed object is
     *     {@link HeaderType }
     *
     */
    public void setHeader(HeaderType value) {
        this.header = value;
    }

    /**
     * Gets the value of the vvInfo property.
     *
     * @return
     *     possible object is
     *     {@link VVNOTICERequest.VVInfo }
     *
     */
    public VVNOTICERequest.VVInfo getVVInfo() {
        return vvInfo;
    }

    /**
     * Sets the value of the vvInfo property.
     *
     * @param value
     *     allowed object is
     *     {@link VVNOTICERequest.VVInfo }
     *
     */
    public void setVVInfo(VVNOTICERequest.VVInfo value) {
        this.vvInfo = value;
    }

    /**
     * Gets the value of the operations property.
     *
     * @return
     *     possible object is
     *     {@link VVNOTICERequest.Operations }
     *
     */
    public VVNOTICERequest.Operations getOperations() {
        return operations;
    }

    /**
     * Sets the value of the operations property.
     *
     * @param value
     *     allowed object is
     *     {@link VVNOTICERequest.Operations }
     *
     */
    public void setOperations(VVNOTICERequest.Operations value) {
        this.operations = value;
    }

    /**
     * Gets the value of the cnt property.
     *
     * @return
     *     possible object is
     *     {@link CNTType }
     *
     */
    public CNTType getCNT() {
        return cnt;
    }

    /**
     * Sets the value of the cnt property.
     *
     * @param value
     *     allowed object is
     *     {@link CNTType }
     *
     */
    public void setCNT(CNTType value) {
        this.cnt = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Operation" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="OperType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="OperDateTime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "operation"
    })
    public static class Operations {

        @XmlElement(name = "Operation", required = true)
        protected List<VVNOTICERequest.Operations.Operation> operation;

        /**
         * Gets the value of the operation property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the operation property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOperation().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link VVNOTICERequest.Operations.Operation }
         *
         *
         */
        public List<VVNOTICERequest.Operations.Operation> getOperation() {
            if (operation == null) {
                operation = new ArrayList<VVNOTICERequest.Operations.Operation>();
            }
            return this.operation;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="OperType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="OperDateTime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "operType",
            "operDateTime"
        })
        public static class Operation {

            @XmlElement(name = "OperType", required = true)
            protected String operType;
            @XmlElement(name = "OperDateTime", required = true)
            protected String operDateTime;

            /**
             * Gets the value of the operType property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getOperType() {
                return operType;
            }

            /**
             * Sets the value of the operType property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setOperType(String value) {
                this.operType = value;
            }

            /**
             * Gets the value of the operDateTime property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getOperDateTime() {
                return operDateTime;
            }

            /**
             * Sets the value of the operDateTime property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setOperDateTime(String value) {
                this.operDateTime = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="PortCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="VesselName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="VoyageNumberIn" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="VoyageNumberOut" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="callsign" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="ship_line" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "portCode",
        "vesselName",
        "voyageNumberIn",
        "voyageNumberOut",
        "callsign",
        "shipLine"
    })
    public static class VVInfo {

        @XmlElement(name = "PortCode", required = true)
        protected String portCode;
        @XmlElement(name = "VesselName", required = true)
        protected String vesselName;
        @XmlElement(name = "VoyageNumberIn", required = true)
        protected String voyageNumberIn;
        @XmlElement(name = "VoyageNumberOut", required = true)
        protected String voyageNumberOut;
        @XmlElement(required = true)
        protected String callsign;
        @XmlElement(name = "ship_line", required = true)
        protected String shipLine;

        /**
         * Gets the value of the portCode property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getPortCode() {
            return portCode;
        }

        /**
         * Sets the value of the portCode property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setPortCode(String value) {
            this.portCode = value;
        }

        /**
         * Gets the value of the vesselName property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getVesselName() {
            return vesselName;
        }

        /**
         * Sets the value of the vesselName property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setVesselName(String value) {
            this.vesselName = value;
        }

        /**
         * Gets the value of the voyageNumberIn property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getVoyageNumberIn() {
            return voyageNumberIn;
        }

        /**
         * Sets the value of the voyageNumberIn property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setVoyageNumberIn(String value) {
            this.voyageNumberIn = value;
        }

        /**
         * Gets the value of the voyageNumberOut property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getVoyageNumberOut() {
            return voyageNumberOut;
        }

        /**
         * Sets the value of the voyageNumberOut property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setVoyageNumberOut(String value) {
            this.voyageNumberOut = value;
        }

        /**
         * Gets the value of the callsign property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getCallsign() {
            return callsign;
        }

        /**
         * Sets the value of the callsign property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setCallsign(String value) {
            this.callsign = value;
        }

        /**
         * Gets the value of the shipLine property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getShipLine() {
            return shipLine;
        }

        /**
         * Sets the value of the shipLine property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setShipLine(String value) {
            this.shipLine = value;
        }

    }

}
