//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.07.21 at 07:22:32 PM UTC
//


package com.example.soapservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VV_NOTICEType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="VV_NOTICEType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="VV_info" type="{http://www.example.com/soapservice}VV_infoType"/&gt;
 *         &lt;element name="Operations" type="{http://www.example.com/soapservice}OperationsType"/&gt;
 *         &lt;element name="CNT" type="{http://www.example.com/soapservice}CNTType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VV_NOTICEType", propOrder = {
    "vvInfo",
    "operations",
    "cnt"
})
public class VVNOTICEType {

    @XmlElement(name = "VV_info", required = true)
    protected VVInfoType vvInfo;
    @XmlElement(name = "Operations", required = true)
    protected OperationsType operations;
    @XmlElement(name = "CNT", required = true)
    protected CNTType cnt;

    /**
     * Gets the value of the vvInfo property.
     *
     * @return
     *     possible object is
     *     {@link VVInfoType }
     *
     */
    public VVInfoType getVVInfo() {
        return vvInfo;
    }

    /**
     * Sets the value of the vvInfo property.
     *
     * @param value
     *     allowed object is
     *     {@link VVInfoType }
     *
     */
    public void setVVInfo(VVInfoType value) {
        this.vvInfo = value;
    }

    /**
     * Gets the value of the operations property.
     *
     * @return
     *     possible object is
     *     {@link OperationsType }
     *
     */
    public OperationsType getOperations() {
        return operations;
    }

    /**
     * Sets the value of the operations property.
     *
     * @param value
     *     allowed object is
     *     {@link OperationsType }
     *
     */
    public void setOperations(OperationsType value) {
        this.operations = value;
    }

    /**
     * Gets the value of the cnt property.
     *
     * @return
     *     possible object is
     *     {@link CNTType }
     *
     */
    public CNTType getCNT() {
        return cnt;
    }

    /**
     * Sets the value of the cnt property.
     *
     * @param value
     *     allowed object is
     *     {@link CNTType }
     *
     */
    public void setCNT(CNTType value) {
        this.cnt = value;
    }

}
